<?php
/**
 * @file
 * A registration form.
 */

/**
 * Implements hook_form_alter().
 */
function registration_form_alter(&$form, &$form_state, $form_id) {
  if (!($form_id == 'user_register_form' || $form_id == 'user_profile_form')) {
    return NULL;
  }
  $n2 = $ln = $ya = $yad = $inf = $agr = '';
  $ot = NULL;
  $toc = [];
  if (!empty($form_state['user'])) {
    $n2 = $form_state['user']->name2;
    $ln = $form_state['user']->last_name;
    $ya = $form_state['user']->your_age;
    $yad = $form_state['user']->your_address;
    $toc = unserialize($form_state['user']->types_of_cats);
    $inf = $form_state['user']->information;
    $agr = $form_state['user']->agreement;
    $ot = array_pop($toc);
  }
  $form['account']['name']['#weight'] = 0;
  $form['account']['mail']['#weight'] = 1;
  $form['account']['name2'] = array(
    '#type' => 'textfield',
    '#title' => t('First name:'),
    '#weight' => 2,
    '#required' => TRUE,
    '#default_value' => $n2,
  );
  $form['last_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Last name:'),
    '#weight' => 3,
    '#required' => TRUE,
    '#default_value' => $ln,
    '#location' => 'http://cats/user/21#overlay-context=node',
  );

  $form['your_age'] = array(
    '#type' => 'textfield',
    '#title' => t('Your age:'),
    '#size' => 3,
    '#weight' => 4,
    '#required' => TRUE,
    '#default_value' => $ya,
  );
  $form['your_address'] = array(
    '#type' => 'textfield',
    '#title' => t('Your address:'),
    '#weight' => 5,
    '#required' => TRUE,
    '#default_value' => $yad,
  );
  $form['types_of_cats'] = array(
    '#weight' => 6,
    '#type' => 'checkboxes',
    '#title' => t('Choose your favourite cat breeds:'),
    '#created' => REQUEST_TIME,
    '#options' => registration_cats_array(),
    '#default_value' => $toc,
  );
  $form['other'] = array(
    '#type' => 'textfield',
    '#weight' => 7,
    '#states' => array(
      'visible' => array(
        ':input[name="types_of_cats[other_type]"]' => array('checked' => TRUE),
      ),
    ),
    '#default_value' => $ot,
  );
  $form['information'] = array(
    '#type' => 'textfield',
    '#title' => t('Please give us some information about yourself.'),
    '#weight' => 8,
    '#required' => TRUE,
    '#default_value' => $inf,
  );
  $form['#validate'][] = 'registration_user_form_validate';
  $form['agreement'] = array(
    '#weight' => 9,
    '#type' => 'radios',
    '#title' => t('By registering at %site-name, you should agree to like cats:))',
      array('%site-name' => variable_get('site_name', 'drupal'))),
    '#options' => array(t('I disagree'), t('I agree')),
    '#default_value' => $agr,
  );
  array_unshift($form['#submit'], 'registration_form_submit');
}

/**
 * Function registration_cats_array().
 */
function registration_cats_array() {
  return array(
    t('American Bobtail Cat'),
    t('Bengal Cats'),
    t('British Shorthair'),
    t('Sphynx'),
    t('Somali'),
    t('Persian'),
    t('European Burmese'),
    t('Devon Rex'),
    t('Without breed'),
    t('I do not have a favourite breed'),
    'other_type' => t('Other'),
  );
}

/**
 * Function registration_user_form_validate().
 */
function registration_user_form_validate($form, &$form_state) {
  if ($form_state['input']['agreement'] <> 1) {
    form_set_error('agreement', t('You must agree!'));
  }
  $minimum_length = 50;
  if (strlen($form_state['values']['information']) < $minimum_length) {
    form_set_error('information', 'The name is too short; minimum length is 50 characters.');
  }
}

/**
 * Function registration_form_submit().
 */
function registration_form_submit($form, &$form_state) {
  array_push($form_state['values']['types_of_cats'], $form_state['values']['other']);
  $form_state['values']['types_of_cats'] = serialize($form_state['values']['types_of_cats']);
  drupal_set_message(t('The form has been submitted.'));
}

/**
 * Implements hook_preprocess_hook().
 */
function registration_preprocess_user_profile(&$variables, &$form) {
  $variables['user_profile']['user_picture']['#weight'] = 0;
  $variables['user_profile']['summary']['#weight'] = 7;
  $variables['user_profile']['name2'] = array(
    '#markup' => '<div><strong> Name: </strong>' . $variables['elements']['#account']->name2 . '</div>',
    '#weight' => 1,
  );
  $variables['user_profile']['last_name'] = array(
    '#markup' => '<div><strong>Last name: </strong>' . $variables['elements']['#account']->last_name . '</div>',
    '#weight' => 2,
  );
  $variables['user_profile']['your_age'] = array(
    '#markup' => '<div><strong>Age: </strong>' . $variables['elements']['#account']->your_age . '</div>',
    '#weight' => 3,
  );
  $variables['user_profile']['your_address'] = array(
    '#markup' => '<div><strong>Address: </strong>' . $variables['elements']['#account']->your_address . '</div>',
    '#weight' => 4,
  );
  $variables['user_profile']['information'] = array(
    '#markup' => '<div><strong>Short bio: </strong>' . $variables['elements']['#account']->information . '</div>',
    '#weight' => 5,
  );
  $cats = array();
  $cats_array = registration_cats_array();
  $selected_cats = $variables['elements']['#account']->types_of_cats;
  $selected_cats = unserialize($selected_cats);
  $i = 0;
  foreach ($cats_array as $key => $cat) {
    if ($selected_cats[$i] == $i) $cats[] = $cat;
    $i++;
  }
  if ($selected_cats[10] != NULL) $cats[] = $selected_cats[10];
  $variables['user_profile']['types_of_cats'] = array(
    '#markup' => '<div><strong>Favourite cat breeds: </strong> <br>' . implode('<br>', $cats) . '</div>',
    '#weight' => 6,
  );
}
